repos:
    - repo: https://github.com/standard/standard
      rev: v17.0.0
      hooks:
        - id: standard
          files: src/blueink/
          exclude: (src/blueink/example/list_bundles.js, src/blueink/seed/)
          verbose: true
          entry: bash -c 'standard --fix "$@" || true' --